const member = [
    {
        "id": "sattm1",
        "name": "Thambu",
        "role": "Founder & Director",
        "image": "/images/Thambu.jpg",
        "level": "director",
        "description": 'Visionary behind SAT Academy, responsible for strategic leadership and innovation.',
        "linkedin": "https://linkedin.com/in/thambu",
        "twitter": "",
        "gmail": "thambu@example.com",
        "portfolio": "",
        "facebook": "",
        "instagram": "",
        "github": ""
    },
    {
        "id": "sattm2",
        "name": "Sreenath",
        "role": "Co-Founder",
        "image": "/images/cofounder.jpg",
        "level": "executive",
        "description": "Empowering students with future-ready skills.",
        "linkedin": "",
        "twitter": "https://twitter.com/anitaroy",
        "gmail": "anita@example.com",
        "portfolio": "https://anitaroy.com",
        "facebook": "",
        "instagram": "",
        "github": ""
    },
    {
        id: "sattm3",
        name: 'Teja Ansury',
        role: 'Managing Director',
        image: '/images/Teja.jpg',
        level: 'executive',
        description: 'Coordinates departments and ensures smooth operations of the academy.',
        "linkedin": "",
        "twitter": "https://twitter.com/anitaroy",
        "gmail": "anita@example.com",
        "portfolio": "https://anitaroy.com",
        "facebook": "",
        "instagram": "",
        "github": ""
    },
    {
        id: "sattm4",
        name: 'Aneesha Shaik',
        role: 'CEO',
        image: '/images/Aneesha.jpg',
        level: 'executive',
        description: 'Experienced CEO driving strategic partnerships, digital transformation, and business expansion.',
        "linkedin": "",
        "twitter": "https://twitter.com/anitaroy",
        "gmail": "anita@example.com",
        "portfolio": "https://anitaroy.com",
        "facebook": "",
        "instagram": "",
        "github": ""
    },
    // {
    //     id: "sattm5",
    //     name: 'Sneha Mehra',
    //     role: 'COO',
    //     image: '/images/coo.jpg',
    //     level: 'senior',
    //     description: 'Leads day-to-day operations with precision, ensuring efficiency and student satisfaction across programs.'
    // },
    // {
    //     id: "sattm6",
    //     name: 'Rakesh Yadav',
    //     role: 'Program Head',
    //     image: '/images/programhead.jpg',
    //     level: 'senior',
    //     description: 'Academic Director with deep technical knowledge and a passion for transforming education delivery.',
    //     "linkedin": "",
    //     "twitter": "https://twitter.com/anitaroy",
    //     "gmail": "anita@example.com",
    //     "portfolio": "https://anitaroy.com",
    //     "facebook": "",
    //     "instagram": "",
    //     "github": ""

    // },
    // {
    //     id: "sattm7",
    //     name: 'Nisha Kulkarni',
    //     role: 'Training Manager',
    //     image: '/images/training.jpg',
    //     level: 'mid',
    //     description: 'Designs and delivers top-quality training programs ensuring students are job-ready from day one.',
    //     "linkedin": "",
    //     "twitter": "https://twitter.com/anitaroy",
    //     "gmail": "anita@example.com",
    //     "portfolio": "https://anitaroy.com",
    //     "facebook": "",
    //     "instagram": "",
    //     "github": ""
    // },
    {
        id: "sattm8",
        name: 'Mahita Sai',
        role: 'Placement Officer',
        image: '/images/Mahita.jpg',
        level: 'mid',
        description: 'Connects learners with industry through strong placement support and employer relations.',
        "linkedin": "",
        "twitter": "https://twitter.com/anitaroy",
        "gmail": "anita@example.com",
        "portfolio": "https://anitaroy.com",
        "facebook": "",
        "instagram": "",
        "github": ""
    },
    {
        id: "sattm9",
        name: 'Vinit Karatagi',
        role: 'Tech Architect (FSD)',
        image: '/images/fsd.jpg',
        level: 'junior',
        description: 'Strategic thinker overseeing operations and full-stack crafting hands-on curricula for developers.',
        "linkedin": "",
        "twitter": "https://twitter.com/anitaroy",
        "gmail": "anita@example.com",
        "portfolio": "https://vinit-portfolio-ochre.vercel.app/",
        "facebook": "",
        "instagram": "",
        "github": ""
    },
    {
        id: "sattm10",
        name: 'M M Khan ',
        role: 'Tech Architect (QA/Test)',
        image: '/images/Khan.jpg',
        level: 'junior',
        description: 'QA lead developing robust testing modules and automation training with real-world practices.',
        "linkedin": "",
        "twitter": "https://twitter.com/anitaroy",
        "gmail": "anita@example.com",
        "portfolio": "https://anitaroy.com",
        "facebook": "",
        "instagram": "",
        "github": ""
    }
];
export default member;